# https://docs.github.com/code-security/dependabot/working-with-dependabot/dependabot-options-reference
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 3
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "10:00"
      timezone: "Asia/Tokyo"
    cooldown:
      default-days: 5
      include:
        - '*'

  - package-ecosystem: "docker"
    directory: "/"
    open-pull-requests-limit: 3
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "10:00"
      timezone: "Asia/Tokyo"
    cooldown:
      default-days: 5
      include:
        - '*'
    # ignore:
    #   - dependency-name: "*"
    #     update-types: ["version-update:semver-major"]

  - package-ecosystem: "gomod"
    directory: "/"
    open-pull-requests-limit: 5
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "10:00"
      timezone: "Asia/Tokyo"
    cooldown:
      default-days: 5
      semver-patch-days: 3
      semver-minor-days: 7
      semver-major-days: 15
      include:
        - '*'
    # ignore:
    #   - dependency-name: "*"
    #     update-types: ["version-update:semver-major"]
    groups:
      gomod:
        update-types: ["minor", "patch"]
        patterns:
          - "*"
