# https://docs.github.com/code-security/dependabot/working-with-dependabot/dependabot-options-reference
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 3
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "10:00"
      timezone: "Asia/Tokyo"

  - package-ecosystem: "docker"
    directory: "/"
    open-pull-requests-limit: 3
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "10:00"
      timezone: "Asia/Tokyo"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "gomod"
    directory: "/"
    open-pull-requests-limit: 5
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "10:00"
      timezone: "Asia/Tokyo"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    groups:
      gomod:
        update-types: ["major", "minor", "patch"]
        patterns:
          - "*"
