name: Build
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**/*.md"
      - ".git*"
      - ".vscode/**"

jobs:
  build:
    name: npm run build
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Install dependencies
        run: go get .
      - name: Build
        run: go build -v ./...
