name: Build
on:
  pull_request:
    branches:
      - main
    paths:
      - "main.go"
      - "cmd/**"
      - "pkg/**"
      - "go.mod"
      - "go.sum"
      - "Dockerfile"
      - ".github/workflows/build.yml"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache: true

      - name: Install dependencies
        run: go mod download

      - name: Build go
        run: go build -v ./...
