name: Lint
on:
  push:
    branches:
      - develop
    paths-ignore:
      - "**/*.md"
      - ".git*"
      - ".vscode/**"

  pull_request:
    branches:
      - main
      - develop
    paths-ignore:
      - "**/*.md"
      - ".git*"
      - ".vscode/**"

jobs:
  lint:
    name: npm run lint
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Run lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
